name: CD
on:
  release:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.1.0
        with:
          run_install: |
            - args: [--frozen-lockfile]
          version: 6.32.3
      - name: Build
        run: npm run ci:build
      - name: Deploy to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
